devices:
  cryostat:
    enabled: false
    driver: drivers.Cryocore.Cryocore
    fallback: drivers.CryoDemo.CryoDemo
  spectrometer:
    enabled: true
    driver: drivers.ThorlabsCCS200.ThorlabsCCS200 # Options: .Heliotis, .Pixis, .OceanSpectrometer,
    fallback: drivers.SpectrometerDemo_advanced.SpectrometerDemo
    init_args:
      port: 'COM10'
  orpheus:
    enabled: false
    driver: drivers.orpheus.Orpheus
  powermeter:
    enabled: false
    driver: drivers.powermeter.ThorlabsPM100D
    fallback: drivers.powermeter.ThorlabsPM100DDemo
  arduino:
    enabled: false
    driver: drivers.Arduino.Arduino
    fallback: drivers.ArduinoDemo.ArduinoDemo
    init_args:
      port: COM14
  piezos:
    enabled: false
    driver: drivers.piezos.Piezos
    init_args:
      port: COM9
  lakeshore:
    enabled: false
    driver: drivers.lakeshore.Lakeshore
  PI863:
    enabled: false
    driver: drivers.PI863.PI863
    fallback: drivers.PI863Demo.PI863Demo
  Lock_In:
    enabled: false
    driver: drivers.Lock_In.Lock_In
    fallback: drivers.Lock_InDemo.Lock_InDemo
comment: 'User: DT

  Sample:

  Power:

  Wavelength:

  Freq: '
