name: Generate documentation
run-name: ${{ github.actor }} is generating documentation for this push
on: [push]
jobs:
  generate_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependancies
      - run: sudo apt-get install doxygen
      - name: Generate documentation
      - run: doxygen doxygen.conf

