import os # interaction with the operating system
import sys # manipulate Python runtime environment
import subprocess # simultaneously running notebook code and web server with html documentation
import time # use time-related functions

import numpy as np # storage and mathematical analysis of camera data
import matplotlib.pyplot as plt # plotting results
import ipywidgets as widgets # interactive control elements

from harvesters.core import Harvester # camera control via GenICam
from packaging.version import parse # compare package versions

import warnings
warnings.simplefilter('always') # show all warnings
# Suppress deprecation warnings generated by ipywidgets 8.1.1 after matplotlib import
warnings.filterwarnings('ignore', module='ipywidgets',category=DeprecationWarning)

#%% load camera
h = Harvester()
# Find (the driver software) Diaphus' CTI-file via environment variable ...
pathToDiaphusCtiFile = os.getenv("DIAPHUS_GENTL64_FILE")
# ... and declare its location to harvesters.
h.add_file(pathToDiaphusCtiFile)
h.update()
options = [f"{dev.id_}  (SN: \"{dev.serial_number}\")" for dev in h.device_info_list]
description = f"{len(h.device_info_list)} device(s) detected : "

w = widgets.RadioButtons(options=options, description=description,layout={'width': 'max-content'},style= {'description_width': 'initial'})
print(w)

camera = h.create(w.index) # create a camera object for the selected device

#%% configure camera

def measurementInitConfig(camera, measurementInitiationMode='external'):
    """
    Configure RecordingStart trigger depending on whether the measurement
    is to be initiated via an internal (software) generated signal
    or an external real-time input through a physical D3 pin.
    """

    camera.remote_device.node_map.TriggerSelector.value = 'RecordingStart'

    if measurementInitiationMode == 'internal':

        camera.remote_device.node_map.TriggerMode.value = 'Off'

    elif measurementInitiationMode == 'external':

        camera.remote_device.node_map.TriggerMode.value = 'On'
        camera.remote_device.node_map.TriggerSource.value = 'FI2'

    camera.remote_device.node_map.TriggerSelector.value = 'FrameStart'
    camera.remote_device.node_map.TriggerMode.value = 'On'
    camera.remote_device.node_map.TriggerSource.value = 'Software'


def lockInAmplificationConfig(camera, sensitivity=0.5, TimeConstant=10, BlankDuration=0, coupling='DC',
                              referenceFrequency=10000, referenceSourceType='Internal',
                              referenceSourceSignal='FI3', referenceFrequencyScaler='Off',
                              expectedFrequencyDeviation=1):
    """
    Configure the heliCam C4's lock-in amplification.
    """

    camera.remote_device.node_map.LockInSensitivity.value = sensitivity
    camera.remote_device.node_map.LockInTargetTimeConstantNPeriods.value = TimeConstant
    if parse(camera.remote_device.node_map.DeviceFirmwareVersion.value) > parse('1.9.2'):
        camera.remote_device.node_map.LockInTargetBlankDurationNPeriods.value = BlankDuration
    camera.remote_device.node_map.LockInCoupling.value = coupling
    camera.remote_device.node_map.LockInTargetReferenceFrequency.value = referenceFrequency

    if referenceSourceType == 'Internal':

        camera.remote_device.node_map.LockInReferenceSourceType.value = 'Internal'

    elif referenceSourceType == 'External':

        camera.remote_device.node_map.LockInReferenceSourceType.value = 'External'
        camera.remote_device.node_map.LockInReferenceSourceSignal.value = referenceSourceSignal
        camera.remote_device.node_map.LockInReferenceFrequencyScaler.value = referenceFrequencyScaler
        camera.remote_device.node_map.LockInExpectedFrequencyDeviation.value = expectedFrequencyDeviation


#camera settings
camera.remote_device.node_map.DeviceOperationMode.value = 'LockInCam'